[versions]
activityCompose = "1.10.0"
activityKtx = "1.10.0"
appcompat = "1.7.0"
composeBom = "2025.02.00"
constraintlayout = "2.2.0"
converterGson = "2.9.0"
coreKtx = "1.15.0"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.1.2"
espressoCore = "3.6.1"
firebaseAuthKtx = "23.2.0"
firebaseBom = "33.9.0"
firebaseInstallations = "18.0.0"
junit = "4.13.2"
junitVersion = "1.2.1"
kotlinxCoroutinesCore = "1.3.5"
ktx = "2.8.7"
legacySupportV4 = "1.0.0"
lifecycleCommonJava8 = "2.8.7"
loggingInterceptor = "4.12.0"
material = "1.12.0"
picasso = "2.5.2"
playServicesAuth = "21.3.0"
preferenceKtx = "1.2.1"
recaptcha = "18.7.0"
recyclerview = "1.4.0"
recyclerviewfastscroller = "1.0.0"
retrofit = "2.9.0"
swiperefreshlayout = "1.1.0"
workRuntimeKtx = "2.10.0"

android = "8.7.3"
googleServices = "4.4.2"
jetbrainsKotlin = "2.1.0"

[libraries]
activity = { module = "androidx.activity:activity", version.ref = "activityCompose" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "coreSplashscreen" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-installations = { module = "com.google.firebase:firebase-installations", version.ref = "firebaseInstallations" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx" }
google-firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycleCommonJava8" }
lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "ktx" }
lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "ktx" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "ktx" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material3 = { module = "androidx.compose.material3:material3" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "ktx" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
recaptcha = { module = "com.google.android.recaptcha:recaptcha", version.ref = "recaptcha" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
recyclerviewfastscroller = { module = "com.quiph.ui:recyclerviewfastscroller", version.ref = "recyclerviewfastscroller" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
ui = { module = "androidx.compose.ui:ui" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android" }
android-library = { id = "com.android.library", version.ref = "android" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlin" }
org-jetbrains-kotlin-kapt-no-version = { id = "org.jetbrains.kotlin.kapt" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "jetbrainsKotlin" }

